name: Publish

env:
  SOLUTION_PATH: allure-csharp.sln
  BUILD_CONFIGURATION: 'Publish'
  PACKAGE_OUTPUT_PATH: 'artifacts'

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup .NET Core SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - name: 'Restore packages'
        shell: pwsh
        run: |
          dotnet restore ${{ env.SOLUTION_PATH }}

      - name: 'Resolve sn.exe location'
        id: find-snexe
        shell: pwsh
        run: |
          $SnExeLocation = ./build/findvstool.ps1 -ToolName 'sn.exe'
          Write-Host "Found '$SnExeLocation'"
          "path=$SnExeLocation" >> $Env:GITHUB_OUTPUT

      - name: 'Build project using dotnet'
        shell: pwsh
        run: |
          dotnet build ${{ env.SOLUTION_PATH }} `
            --no-restore `
            --configuration ${{ env.BUILD_CONFIGURATION }} `
            -p:ContinuousIntegrationBuild=true `
            "-p:Allure_SnExePath=${{ steps.find-snexe.outputs.path }}"

      - name: Verify assembly strong names
        shell: pwsh
        run: |
          $SnExe = "${{ steps.find-snexe.outputs.path }}"
          Get-ChildItem "./*/bin/*/*/Allure.*.dll" -Exclude "Allure.SpecFlow*","Allure.Xunit*" | ForEach-Object {
            & $SnExe -vf $_.FullName
          }

      - name: 'Pack project'
        shell: pwsh
        run: |
          dotnet pack ${{ env.SOLUTION_PATH }} `
            --no-restore `
            --no-build `
            --configuration ${{ env.BUILD_CONFIGURATION }} `
            "-p:PackageReleaseNotes=${{ github.event.release.html_url }}" `
            "-p:PackageOutputPath=${{ github.workspace }}/${{ env.PACKAGE_OUTPUT_PATH }}"

      - name: 'NuGet publish'
        shell: pwsh
        run: |
          dotnet nuget push "${{ env.PACKAGE_OUTPUT_PATH }}/*.nupkg" `
            --api-key "$Env:NUGET_TOKEN" `
            --source "https://api.nuget.org/v3/index.json"
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
